### ISSUE TITLE
Configurable automatic charging separation

### ISSUE THREAD

**Issue by langerhans** [langerhans/OdinTools#21]
Automatically turn on/off charging separation at user selectable battery levels

**Comment by miguelguzmanr** [comment]
Notes
====

### Settings

| Name | Type | Command |
| ----------- | ----------- | ----------- |
| Charging separation | Boolean | `settings get system is_charging_separation` |
| Restrict current | Int | `cat /sys/class/qcom-battery/restrict_cur /sys/class/qcom-battery/restrict_cur` |
| Restrict charge | Boolean | `cat /sys/class/qcom-battery/restrict_cur /sys/class/qcom-battery/restrict_chg` |

### Values

| State | Charging separation | Restrict current | Restrict charge |
| ----------- | ----------- | ----------- | ----------- |
| 🔋 Charging | 0 | 1000000 | 0 |
| ⚡ Bypass charging | 1 | 1000 | 1 |

**Comment by miguelguzmanr** [comment]
Unable to implement as-is due to charging separation not switching off as expected.

Currently, under device version `1.0.0.266`, turning off charging separation while plugged in will not resume charging. You must re-plug your device to resume charging again.

Thanks to @langerhans for discovering and reporting this issue.

Might look into it later if fixed in a future update.

**Comment by miguelguzmanr** [comment]
Seems to be working on device version `1.0.0.288`!

**Comment by miguelguzmanr** [comment]
Closed by #28
